baseurl = "www.anniekatelyntang.com"
title = "Annie K Tang"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]
publishDir = "docs"

[params]
  description = '<!--[-->Incoming Research Engineer @ Apple<!--]-->'
  logo = "fa-hand-peace-o"
  copyright = "Annie Katelyn Tang"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/anniekatelyntang/"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  url = "https://www.instagram.com/anniekatelyntang/"

[[params.social]]
  medium = "github"
  icon = "github"
  url = "https://github.com/anniekatelyn"

[languages]
[languages.en]
languageName = "English"
weight = 1
